services:
  fortiweb-analytics:
    build: .
    container_name: fortiweb-dashboard
    restart: unless-stopped
    ports:
      - "9000:5000"
    # This loads the variables from the .env file
    env_file:
      - .env
    # This ensures your history database persists even if you rebuild the container
    volumes:
      - ./stats.db:/app/stats.db
